version: 2.1

jobs:
  hello-stinky-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Ahoy, Stinky!"

workflows:
  hello-florld-florkflow:
    jobs:
      - hello-stinky-job
